# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://Ridorandika1.github.io
title: MONA FRONITA
email: your-email@domain.com
author: rido
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Rido randika putra. All Rights  Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: JADWAL BIMBINGAN PA 
    url: http://sif.uin-suska.ac.id/
  - title: JADWAL BIMBINGAN TA
    url: http://uin-suska.ac.id/
  - title: JADWAL BIMBINGAN KP
    url: http://youtube.com
